[package]
name = "sqweal"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
iso_currency = { version = "0.4.4", features = ["serde"] }
oxydized-money = "0.3.0"
oxydized-money-macros = "0.2.0"
rust_decimal = "1.34.3"
rust_decimal_macros = "1.34.2"
serde = { version = "1.0.197", features = ["derive"] }
sqlx = { version = "0.7.4", features = [
    "chrono",
    "postgres",
    "runtime-tokio",
    "rust_decimal",
    "macros",
] }
tokio = { version = "1.36.0", features = ["full"] }
