[package]
name = "miniorm-example-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = "0.7.4"
miniorm-macros = { path = "../../macros" }
miniorm = { path = "../../" }
dotenv = "0.15.0"
tokio = { version = "1.36.0", features = ["full"] }
