name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Test with default feature
        run: cargo test --workspace
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Postgres and MySql sandbox
        run: docker compose up -d
      - name: Run all integration tests
        run: cargo test -F integration_tests
      - name: Stop Postgres sandbox
        run: docker compose down
